### ISSUE TITLE
Review: I see no nodes / Http_CreateRequestFailed

### ISSUE THREAD

**Issue by cgravill** [CSBiology/FSharpGephiStreamer#16]
**Describe the bug**
When attempting to create nodes I'm getting this exception: Http_CreateRequestFailed 

Note while I started with the install instructions as they are at: https://csbiology.github.io/FSharpGephiStreamer/exampleAnalysis.html I made some adjustments. What you're currently doing:

```fsharp
let addOboNode (node:GONode) =

    let nodeConverter (node:GONode) =
        [
            Grammar.Attribute.Label (sprintf "%s | %s {%s}" node.Id node.TermDescription node.NameSpace); 
            Grammar.Attribute.Size  10.; 
            Grammar.Attribute.Color node.Color; 
            Grammar.Attribute.UserDef ("UserData",node.TermDescription); 
        ]
    Streamer.addNode nodeConverter node.Id node

goNodes |> List.map addOboNode
```

means that you're masking errors with the implicit ignore on the `List.map` (which generates warnings). I suggest you need to choose, if you're going to use the `Either` monad then it's important to include that in your examples 

As to the actual error, I do have Gephi running but perhaps there's an access issue? Any guidance on debugging this?

**Expected behavior**
Nodes and edges into Gephi

**OS and framework information (please complete the following information):**
 - OS: Windows 10
 - .Net core SDK version [e.g. 2.2.203 ]

**Additional context**
This is possibly related to #15 perhaps I have the wrong version for you?

https://github.com/openjournals/joss-reviews/issues/1445

**Comment by kMutagene** [comment]
The streamer sends the edge and node data to a local server created by the graph streaming plugin.

So additionally to #15 (the creation of the Json failing due to the missing Newtonsoft.Json dependency), i could imagine two problems that could cause this:

 1. the streaming master server is not enabled :
  
![image](https://user-images.githubusercontent.com/21338071/58791706-fcb7e200-85f2-11e9-86a3-9022c51eb757.png)

 2. We stream nodes and edges to the following workspace per default: 
   `"http://localhost:8080/workspace1?operation=updateGraph"` (workspace 1). 
    if you have workspaces with other names you can change the target url by using the `setEnvironment` function as seen here :

![image](https://user-images.githubusercontent.com/21338071/58791873-528c8a00-85f3-11e9-9ec2-7e48879bd940.png)

Edit: I just saw that the information that you have to create a workspace in gephi is missing from the docs, ill fix that.

**Comment by kMutagene** [comment]
I have a hard time reproducing your error. I opened a new script and created the following dependency file in the same folder: 

```
generate_load_scripts: true

source https://www.nuget.org/api/v2

nuget FSharpGephiStreamer
```

If i now create a script file with the generated loading script (`main.group.fsx`), and use the functions provided in the [streaming docs](https://csbiology.github.io/FSharpGephiStreamer/Streaming.html):

```
#load @"C:\Users\Kevin\source\scripts\GephiStreamerTest\.paket\load\netstandard2.1\main.group.fsx"

open FSharpGephiStreamer

/// Record type that represents a custom node 
type MyNode = {
    Id    : int
    Label : string
    Size  : float
    Data  : string
    }

/// Record type that represents a custom edge 
type MyEdge = {
    Id :     int
    Source : int
    Target : int
    Weight : float    
    }

///converts a MyNode type to a list of grammar attributes
let nodeConverter (node:MyNode) =
    [
        Grammar.Attribute.Label node.Label; 
        Grammar.Attribute.Size  node.Size; 
        Grammar.Attribute.Color (Colors.Table.StatisticalGraphics24.getRandomColor()); 
        Grammar.Attribute.UserDef ("UserData",node.Data); 
    ]

///converts a MyEdge type to a list of grammar attributes
let edgeConverter (edge:MyEdge) =
    [
        Grammar.Attribute.Size  edge.Weight; 
        Grammar.Attribute.EdgeType  Grammar.EdgeDirection.Undirected;             
        Grammar.Attribute.Color Colors.Table.Office.grey ;      
    ]

///Adds a node of type MyNode using the node converter to the gephi graph
let addMyNode (node:MyNode) = 
    Streamer.addNode nodeConverter node.Id node
    

///Adds an edge of type MyEdge using the edge converter to the gephi graph
let addMyEdge (edge: MyEdge) =
    Streamer.addEdge edgeConverter edge.Id edge.Source edge.Target edge

let myNode = {Id = 1; Label = "FOO" ; Size = 4.; Data = "BAR"}

addMyNode myNode
```

I get a node in gephi with the current nuget package: 

Before (Go to the data laboratory tab in gephi):

![image](https://user-images.githubusercontent.com/21338071/58863340-f38e4a00-86b2-11e9-9354-e2ab0d33b74e.png)

After running the script:

![image](https://user-images.githubusercontent.com/21338071/58863509-3bad6c80-86b3-11e9-9e4f-37787e847a48.png)

Could you guys try this?

Edit: Regarding the issue not seeing nodes: It may also be (Most likely not though, because you guys get the HTTPCreateRequest error), that the node is just out of focus in gephi. That was exactly the case for the node generated in this script here, so you can also try to center the view on the graph:

![image](https://user-images.githubusercontent.com/21338071/58863884-fb022300-86b3-11e9-8730-af3eff375c1c.png)

which for me results in this picture:

![image](https://user-images.githubusercontent.com/21338071/58863909-07867b80-86b4-11e9-886c-1226fa5a106c.png)

**Comment by PrashantVaidyanathan** [comment]
I'm still unable to see any nodes. When I tried the code specified above, I get the following error (I get the same error when I try the other example): 
`Exception thrown: 'System.NullReferenceException' in FSharpGephiStreamer.dll`
`Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.dll`

I do see this in the console: 
`{"an":{"1":{"label":"FOO","size":4.0,"color":"#8DD593","UserData":"BAR"}}}`

However I am still unable to see anything in Gephi. 

I also verified that Gephi was the only process using ports 8080 and 8443.

**Comment by kMutagene** [comment]
@cgravill :
> means that you're masking errors with the implicit ignore on the List.map (which generates warnings). I suggest you need to choose, if you're going to use the Either monad then it's important to include that in your examples

I added this to the new [basic sample](https://csbiology.github.io/FSharpGephiStreamer/SimpleNetwork.html)

Is this sufficient for you?

**Comment by kMutagene** [comment]
@PrashantVaidyanathan 

> I do see this in the console:
{"an":{"1":{"label":"FOO","size":4.0,"color":"#8DD593","UserData":"BAR"}}}

This means that the Json string is created successfully. The error must be happening somewhere around here in the source code:
```

    /// Adds a node to the gephi graph using the given node converters grammar attribute mapping
    let addNode (nodeConverter:NodeConverter<'node>) nodeId =
        let nodeId' = string nodeId
        (Either.tryCatch 

            // This works for you

            (fun (node:'node) ->  (jsonFormatNode Action.Add nodeId' (nodeConverter node)))
            (fun exn  -> Error.CreateJsonFailed exn.Message))
        >> Either.bind (generatePostRequest (getEnvirmonment ()) )
        >> Either.bind evalHttpResponseText
        >> Either.either 
            (fun _     -> Success nodeId' )

            //This fails

            (fun error -> Failure error )
```

However i find it strange that we get a null reference exception here. I uploaded a new package with updated dependencies, I hope this can fix your error.

**Comment by PrashantVaidyanathan** [comment]
I'm still getting a null reference exception (even with the updated dependencies). I think you are right, the error is occurring here: 
`let addMyNode (node:MyNode) = `
`    Streamer.addNode nodeConverter node.Id node`

The specific error is: 
`Exception thrown: 'System.NullReferenceException' in FSharpGephiStreamer.dll ("Object reference not set to an instance of an object.")`

More specifically, the nodeAddResults and edgeAddResults have the following values (for all nodes and edges):
`Http_CreateRequestFailed "Object reference not set to an instance of an object."`

**Comment by kMutagene** [comment]
are you sure you have the right package @PrashantVaidyanathan ? The nuget page lists 0 downloads for 1.1.2:

![image](https://user-images.githubusercontent.com/21338071/58893276-1e4ac380-86f0-11e9-98b8-dcd6ce64f682.png)

**Comment by PrashantVaidyanathan** [comment]
![Screenshot](https://user-images.githubusercontent.com/2364721/58894178-6a463a00-86e9-11e9-8770-f9141565fc0c.png)

Yes. I'm not sure why the nuget page hasn't updated yet though.

**Comment by kMutagene** [comment]
I was finally able to reproduce the error, now that i saw that you are executing it in a console project template. When i do this i get the same:

![image](https://user-images.githubusercontent.com/21338071/59018702-c70b3700-8846-11e9-9ca9-913efebe4483.png)
 
While i am not sure yet why this occurs, have you executed the examples like this all the time? if so, can you try creating a `.fsx` script file and send the code directly to F# interactive? If that works for you (This is how all of this was tested), we at least enclosed the error a bit.

**Comment by kMutagene** [comment]
I found the problem. The Http.fs version we used was encoding uri slashes with a hack using reflection and setting fields of objects. The accession of this field caused the NullReferenceException. I updated the package to use the Http.fs nuget package to handle http request creation and encoding. Streaming nodes and edges should work in program loops too.

**Comment by PrashantVaidyanathan** [comment]
It looks like this update also requires the latest version of Hopac to be installed. I ran into an error using just version 1.1.3  
However, when I installed the latest version of Hopac (https://github.com/Hopac/Hopac) via NuGet, everything started working. So perhaps you could fix this by adding Hopac as a dependency as well (version 0.4.1 or higher)?

**Comment by kMutagene** [comment]
Yeah i just saw that, but this is a strange error as hopac is listed as dependency of Http.fs, not of the package itself. So i don't get why package management does not resolve this. I will check if adding hopac as dependency fixes the problem.

**Comment by PrashantVaidyanathan** [comment]
I can confirm that I was able to run both the examples after I installed hopac as a dependency.

**Comment by kMutagene** [comment]
I think i found the root of this problem:

paket (the package manager we use) uses a different strategy to resolve [transitive dependencies](https://fsprojects.github.io/Paket/dependencies-file.html#Strategy-option) then nuget. This also explains the problems you guys faced with the Newtonsoft.Json package dependency:

While paket resolves transient dependencies with the maximum version, nuget takes the minimum matching version. And this is how we end up with these dependency conflicts. I was not aware of this, sorry for all the confusion.

So what i will do now is emulate the nuget manager behaviour in our paket.dependencies file so that a package can be generated that is compatible with nuget manager out of the box.

Edit:
I think i managed to make the package compatible with both paket and nuget package manager (v1.1.6)

**Comment by PrashantVaidyanathan** [comment]
That seems to have fixed the issue. I just tested v1.1.6 and both the examples seem to work :)
